### ISSUE TITLE
[compliance] Set default figure size and style in _config.yml

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/meta#92]
We need to ensure all QuantEcon lectures add the necessary global config to enable consistent image sizes and style across the lecture series. 

```yaml
sphinx:
  config:
    # myst-nb config
    nb_render_image_options:
      width: 75%
      classes: shadow bg-primary
```

This will be documented in https://github.com/QuantEcon/QuantEcon.manual/pull/18 and become part of the setup guide for QuantEcon lecture repositories. 

- [ ] lecture-datascience.myst                 
- [ ] lecture-econometrics-machine-learning    
- [ ] lecture-jax                              
- [ ] lecture-julia.myst                       
- [ ] lecture-julia.notebooks                  
- [ ] lecture-python-advanced.myst             
- [ ] lecture-python-intro                     
- [ ] lecture-python-programming.myst          
- [ ] lecture-python.docker                    
- [ ] lecture-python.myst

**Comment by HengchengZhang** [comment]
Hi @mmcky , just to confirm that we are now applying this as default configuration
```
sphinx:
  config:
    # myst-nb config
    nb_render_image_options:
      width: 80%
```
